### PR TITLE
feat: http command

### PR DESCRIPTION
**Pull request by patrykcieszkowski**
- [x] http handler
- [x] DNS resolver
- [x] unit tests

resolve https://github.com/jsdelivr/globalping/pull/128

### CODE REVIEW

**Comment by jimaek** [comment]
I dont think the output has everything we need, do you have a sample?

This is what we need:
- performance meta-data: dns lookup, tcp connection, tls handshake, time to first byte, download, total time
- tls certificate meta-data like issuer, domain, issue and expiration date, valid bool...

**Comment by patrykcieszkowski** [comment]
> do you have a sample?

heres the current output:

```json
{
        "headers": {
          "connection": "close",
          "cache-control": "private",
          "content-type": "text/html; charset=utf-8",
          "content-encoding": "gzip",
          "strict-transport-security": "max-age=15552000",
          "x-frame-options": "SAMEORIGIN",
          "x-request-guid": "1706d2e1-63fd-49a8-b15b-b09b92c577e4",
          "feature-policy": "microphone 'none'; speaker 'none'",
          "content-security-policy": "upgrade-insecure-requests; frame-ancestors 'self' https://stackexchange.com",
          "accept-ranges": "bytes",
          "date": "Tue, 24 May 2022 19:42:03 GMT",
          "via": "1.1 varnish",
          "x-served-by": "cache-lhr7383-LHR",
          "x-cache": "MISS",
          "x-cache-hits": "0",
          "x-timer": "S1653421323.041443,VS0,VE73",
          "vary": "Accept-Encoding,Fastly-SSL",
          "x-dns-prefetch-control": "off",
          "set-cookie": [
            "prov=82b27b3b-8094-d9b3-4d53-6140c4ab85f6; domain=.stackoverflow.com; expires=Fri, 01-Jan-2055 00:00:00 GMT; path=/; HttpOnly"
          ]
        },
        "rawHeaders": "Connection: close\ncache-control: private\ncontent-type: text/html; charset=utf-8\ncontent-encoding: gzip\nstrict-transport-security: max-age=15552000\nx-frame-options: SAMEORIGIN\nx-request-guid: 1706d2e1-63fd-49a8-b15b-b09b92c577e4\nfeature-policy: microphone 'none'; speaker 'none'\ncontent-security-policy: upgrade-insecure-requests; frame-ancestors 'self' https://stackexchange.com\nAccept-Ranges: bytes\nDate: Tue, 24 May 2022 19:42:03 GMT\nVia: 1.1 varnish\nX-Served-By: cache-lhr7383-LHR\nX-Cache: MISS\nX-Cache-Hits: 0\nX-Timer: S1653421323.041443,VS0,VE73\nVary: Accept-Encoding,Fastly-SSL\nX-DNS-Prefetch-Control: off\nSet-Cookie: prov=82b27b3b-8094-d9b3-4d53-6140c4ab85f6; domain=.stackoverflow.com; expires=Fri, 01-Jan-2055 00:00:00 GMT; path=/; HttpOnly",
        "rawBody": "",
        "statusCode": 200,
        "responseTime": 451,
        "rawOutput": "HTTP/1.1 200\nConnection: close\ncache-control: private\ncontent-type: text/html; charset=utf-8\ncontent-encoding: gzip\nstrict-transport-security: max-age=15552000\nx-frame-options: SAMEORIGIN\nx-request-guid: 1706d2e1-63fd-49a8-b15b-b09b92c577e4\nfeature-policy: microphone 'none'; speaker 'none'\ncontent-security-policy: upgrade-insecure-requests; frame-ancestors 'self' https://stackexchange.com\nAccept-Ranges: bytes\nDate: Tue, 24 May 2022 19:42:03 GMT\nVia: 1.1 varnish\nX-Served-By: cache-lhr7383-LHR\nX-Cache: MISS\nX-Cache-Hits: 0\nX-Timer: S1653421323.041443,VS0,VE73\nVary: Accept-Encoding,Fastly-SSL\nX-DNS-Prefetch-Control: off\nSet-Cookie: prov=82b27b3b-8094-d9b3-4d53-6140c4ab85f6; domain=.stackoverflow.com; expires=Fri, 01-Jan-2055 00:00:00 GMT; path=/; HttpOnly"
      }
```

**Comment by jimaek** [comment]
Ok, yeah we need to expand the timings array to include everything else. And add a new one for HTTPS/HTTP2 requests about TLS

**Comment by patrykcieszkowski** [comment]
> And we include the private IPs protection without warming up the cache right?

We query the DNS, and in case it responds with multiple records - we filter out all private IPs. If there's none left - it throws an error. If there are records left - we pick the first one.

```
ENODATA google.com
```

**Comment by patrykcieszkowski** [comment]
> Then the warm cache issue persists, doesn't it?

we explicitly disable cache on HTTP requests. DNS wise - I don't believe node DNS resolver caches anything.

**Comment by jimaek** [comment]
Linux caches the query on a system level as far as I know. Plus it gets cached by the resolver you hit. So you pre-warm it in 2 places.

**Comment by jimaek** [comment]
You dont know, you see it based on the results. If you select a less popular domain you will see that the first 1-2 queries are slow, e.g. 10ms and the ones after are fast, e.g. 3ms. 

But the whole point of the service is to benchmark and test services to improve your performance. So users cant get reliable readings then its a problem

**Comment by patrykcieszkowski** [comment]
But the problem is, we can't distinguish which reading is cached, and which wasn't. We could probably store the largest value, and update it accordingly on each reading, but that will also be just guess work on our end. It won't be reliable.

**Comment by jimaek** [comment]
Thats not the point, we shouldn't do anything to decide anything. 
We need:
1. To stop making 2 DNS queries per test
2. If not possible then use the query time of the first query.

**Comment by patrykcieszkowski** [comment]
We're making one query.

**Pull request merged**
