### PR TITLE
feat: prevent private targets

### PR DESCRIPTION
**Pull request by patrykcieszkowski**
- [x] ping final
- [x] ping partial
- [x] traceroute final
- [x] traceroute partial
- [x] dns final
- [x] dns partial

### CODE REVIEW

**Comment by patrykcieszkowski** [comment]
DNS has to wait for PR merge.

**Comment by jimaek** [comment]
trace merged, can be continued

**Comment by MartinKolarik** [comment]
Looks ok but missing tests.

**Comment by patrykcieszkowski** [comment]
tests added

**Pull request merged**
