### PR TITLE
feat: self-update docker image

### LINKED ISSUE #7: Docker container self-update
Assume the user will never pull a new Docker container. We must check if it is possible to do auto-updates within a docker container.

Alternatively, we may bundle the app into a single binary and find the solution to swap binaries with new ones. What is the issue here is that we may want to update `ping`, `traceroute`, or `dig` binaries

### PR DESCRIPTION
**Pull request by zarianec**
resolve #7 

- [ ] add error reporting to appSignal (?)

### CODE REVIEW

**Comment by jimaek** [comment]
Why the extra API endpoint? Why not use Github directly? 
https://api.github.com/repos/jsdelivr/globalping-probe/releases
https://api.github.com/repos/jsdelivr/globalping-probe/releases/latest

1. Sounds good, should be the fastest way to update a slow probe
2. What is the safety issue here? That the user will MITM the probe? He already has root access to it
3. The whole point of the probe is gone then. If the user decides to manual update the probe then in 6 months I guarantee the node goes offline because it will get stuck in some old version. Also the same argument can be used against the jsDelivr CDN, some might not trust it but it's a requirement to use it and over the last 10 years we have not broken that trust.

**Comment by patrykcieszkowski** [comment]
2. Why don't we use `zsync` for instance? http://zsync.moria.org.uk/

**Comment by jimaek** [comment]
> 2. Why don't we use `zsync` for instance? http://zsync.moria.org.uk/

Yeah looks interesting, even faster updates

**Comment by zarianec** [comment]
@jimaek 
2. not the user but anyone else
3. At least we give users a choice so they can't complain about it.

**Comment by zarianec** [comment]
1. Probe code is still included in Docker image to avoid unnecessary network requests when the latest version of the image is used.
2. Default update check interval is 5 minutes + up to 5 additional randomly chosen minutes.
3. Release process is automated and [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) convention must be followed to generate proper release notes.

**Comment by zarianec** [comment]
> Why don't we use zsync for instance?

It requires extra work to be done (generate `.zsync` file along with tgz archive) and, given the size of our file, doesn't make much sense

**Comment by jimaek** [comment]
>Probe code is still included in Docker image to avoid unnecessary network requests when the latest version of the image is used.

Are you sure this wont create maintenance issues due to the duplication? We will basically have 2 differently compiled versions of the probe this way

**Review by jimaek — APPROVED** [review]

**Pull request merged**
